services:
  mysql_service:
    image: mysql:oraclelinux9
    container_name: mysql_db_container_transporte
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: transporte_root
      MYSQL_DATABASE: transporte
      MYSQL_USER: transporte_user
      MYSQL_PASSWORD: password_user
#    volumes:
#      - mysql_data2:/var/lib/mysql
#volumes:
#  mysql_data2: